//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// NoSpearClient.rc에서 사용되고 있습니다.
//
#define IDR_TRAY_MENU                   4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MainView                    101
#define IDD_NOSPEAR_CLIENT_DIALOG       102
#define IDR_MAINFRAME                   127
#define IDD_FILELISTVIEWDIALOG          131
#define IDD_SettingView                 132
#define IDD_QuarantineView              133
#define IDB_PNG1                        136
#define IDI_ICON4                       166
#define IDI_ICON5                       167
#define IDI_ICON6                       168
#define IDI_ICON7                       169
#define IDI_ICON8                       170
#define IDR_FileViewRMENU               171
#define IDI_ICON1                       178
#define IDI_ICON2                       179
#define IDI_ICON3                       180
#define IDI_ICON9                       189
#define IDI_ICON10                      190
#define IDI_ICON11                      191
#define IDI_ICON12                      192
#define IDI_ICON13                      193
#define IDI_ICON14                      194
#define IDI_ICON15                      195
#define IDI_ICON16                      196
#define IDI_ICON17                      197
#define IDB_BITMAP1                     198
#define IDB_BITMAP2                     200
#define IDR_MENU1                       204
#define IDR_Quarantine                  204
#define btn_selectfile                  1001
#define btn_uploadfile                  1002
#define edit_filepath                   1003
#define label_filename                  1011
#define IDC_LIST1                       1012
#define btn_test                        1012
#define btn_activelive                  1012
#define quarantin_list                  1012
#define quarantine_list                 1012
#define IDC_LIST3                       1015
#define btn_inactivelive                1016
#define IDC_BUTTON1                     1018
#define btn_activate                    1018
#define btn_updateClient                1018
#define IDC_LIST2                       1019
#define FileList                        1019
#define IDC_FileListCtrl                1019
#define IDC_BUTTON2                     1020
#define btn_diagnose                    1020
#define btn_inactivateLive              1020
#define btn_SelectFolder                1022
#define IDC_COMBO1                      1023
#define IDC_BUTTON3                     1024
#define IDC_openfolder                  1025
#define IDC_refreshDB                   1026
#define IDC_CHECK1                      1027
#define IDC_CHECK2                      1028
#define IDC_CHECK3                      1029
#define IDC_CHECK4                      1030
#define IDC_CHECK5                      1031
#define IDC_search1                     1032
#define IDC_search2                     1033
#define IDC_search3                     1034
#define IDC_search4                     1035
#define IDC_search5                     1036
#define IDC_refreshlist                 1037
#define IDC_home                        1038
#define IDC_FormViewer                  1039
#define btn_search                      1040
#define IDC_menu                        1041
#define btn_manualDiagnose              1041
#define IDC_fileviewer                  1042
#define IDC_filename                    1042
#define IDC_fileviewer2                 1043
#define IDC_STATIC2                     1043
#define IDC_setting                     1043
#define label_result_filename           1044
#define label_result_filename2          1045
#define label_result_text               1045
#define label_result_report             1046
#define img_liveprotect                 1047
#define img_logo                        1047
#define IDC_STATIC3                     1047
#define logo_frame                      1048
#define IDC_diagnose_status             1049
#define btn_activateLive                1050
#define version_now                     1051
#define version_new                     1052
#define IDC_quarantine                  1053
#define ID_TRAY_NO                      32771
#define ID_TRAY_EXIT                    32772
#define ID_MANU_32773                   32773
#define ID_MANU_ZONE                    32774
#define ID_ADS_0                        32775
#define ID_ADS_3                        32776
#define ID_MANU_ADS                     32777
#define ID_ADS_1                        32778
#define ID_ADS_2                        32779
#define ID_ADS_4                        32780
#define ID_MANU_32781                   32781
#define ID_MANU_32782                   32782
#define ID_MANU_1                       32783
#define ID_MANU_2_0                     32784
#define ID_MANU_2_3                     32785
#define ID_MANU_3_0                     32786
#define ID_MANU_3_1                     32787
#define ID_MANU_3_2                     32788
#define ID_MANU_4                       32789
#define ID_MANU_5                       32790
#define ID_MANU_32791                   32791
#define ID_MANU_6                       32792
#define ID_Menu                         32793
#define ID_QUARANTINE_delete            32797
#define ID_QUARANTINE_recover           32798
#define ID_QUARANTINE_result            32799
#define ID_QUARANTINE_report            32800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
